### PR TITLE
Update to v2.13.0 for `release/100.15.0`

### PR DESCRIPTION
**Pull request by itrombley**
Update `release/100.15.0` to v2.13.0

### CODE REVIEW

**Comment by chri7325** [comment]
Was the freetype upgrade into the runtimecore branch squashed when merged? If so we have to undo all that.

**Comment by itrombley** [comment]
It was. I'll redo it.

**Comment by itrombley** [comment]
This didn't need to be closed. Once `runtimecore` is updated properly then this PR would be valid.

**Comment by chri7325** [comment]
@itrombley I think GitHub closed it on my behalf when I force pushed the branch to drop the commit so it is cleaning up messes.

**Pull request closed without merging**
